name: Publish NPM package

on:
  release:
    types: ["created"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install NPM dependencies
        run: npm install
      - name: Build NPM dependencies
        run: npm run build
      - name: Set version via tag
        run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
