name: Publish NPM package

on:
  release:
    types: ["created"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: npm
      - run: npm install -g npm@11.6.0
      - run: npm install
      - run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}
      - run: npm publish
